### ISSUE TITLE
it looks we need many dependencies for the pom.xml 

### ISSUE THREAD

**Issue by RobinsChens** [Swagger2Markup/spring-swagger2markup-demo#13]
it looks we need many dependencies for the pom.xml ，can you support a easy way to use this tool

**Comment by RobWin** [comment]
Hi, not sure what you mean. Swagger2Markup itself is just 1 Maven Plugin. Everything else is either Spring Boot, Springfox, Spring Rest Docs or AsciiDoctor specific. You can pick what you need.

If you just want to convert a Swagger Spec into Markdown/Asciidoc, you can use the [Gradle](https://github.com/Swagger2Markup/swagger2markup-gradle-project-template)/[Maven](https://github.com/Swagger2Markup/swagger2markup-maven-project-template) Template Projects, [CLI](https://github.com/Swagger2Markup/swagger2markup-cli) oder Docker Image. 
See user guide: http://swagger2markup.github.io/swagger2markup/1.3.1/
