### ISSUE TITLE
Documentation not available when demo is started via gradle bootRun

### ISSUE THREAD

**Issue by gernd** [Swagger2Markup/spring-swagger2markup-demo#19]
This is rather a question than an issue:

Why is it not possible to access the generated static docs when the demo is started via gradle(w) bootRun?

Is is somehow possible?

**Comment by gernd** [comment]
I guess I found out myself :-/
As stated in https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html, bootRun runs the project in place without creating a jar, so the resources are probably not packed

**Comment by RobWin** [comment]
Correct answer :)
